import Foundation

struct LocalizationService {
    static let shared = LocalizationService()

    private let table: [String: [AppLanguage: String]] = [
        "appName": [.zh: "Machi", .ja: "Machi", .en: "Machi"],
        "databaseFallback": [.zh: "数据库已降级为临时模式，重启后数据可能不会保留。", .ja: "データベースは一時モードです。再起動後に保存されない可能性があります。", .en: "Database is running in temporary mode; data may not persist after restart."],
        "home": [.zh: "首页", .ja: "ホーム", .en: "Home"],
        "search": [.zh: "搜索", .ja: "検索", .en: "Search"],
        "discover": [.zh: "发现", .ja: "発見", .en: "Discover"],
        "notifications": [.zh: "通知", .ja: "通知", .en: "Notifications"],
        "messages": [.zh: "私信", .ja: "メッセージ", .en: "Messages"],
        "newMessage": [.zh: "新私信", .ja: "新規メッセージ", .en: "New message"],
        "me": [.zh: "我的", .ja: "自分", .en: "Me"],
        "profile": [.zh: "个人主页", .ja: "プロフィール", .en: "Profile"],
        "settings": [.zh: "设置", .ja: "設定", .en: "Settings"],
        "account": [.zh: "账号", .ja: "アカウント", .en: "Account"],
        "accountSettingsSubtitle": [.zh: "管理资料、安全和本机偏好", .ja: "プロフィール、安全、端末設定を管理", .en: "Manage profile, safety, and local preferences"],
        "accountGroup": [.zh: "账号", .ja: "アカウント", .en: "Account"],
        "accountEssentials": [.zh: "账号资料", .ja: "アカウント情報", .en: "Account details"],
        "accountProfile": [.zh: "账号资料", .ja: "アカウント情報", .en: "Account profile"],
        "accountProfileSubtitle": [.zh: "个人主页、编辑资料和切换账号", .ja: "プロフィール、編集、アカウント切替", .en: "Profile, edit profile, and account switch"],
        "regionAndLanguage": [.zh: "地区与语言", .ja: "地域と言語", .en: "Region and language"],
        "regionAndLanguageSubtitle": [.zh: "国家、界面语言、内容语言与主题", .ja: "国、表示言語、コンテンツ言語、テーマ", .en: "Country, app language, content language, and theme"],
        "countrySetting": [.zh: "国家", .ja: "国", .en: "Country"],
        "countrySettingSubtitle": [.zh: "城市在首页和发现页随时切换", .ja: "都市はホームと発見でいつでも切替", .en: "Cities switch right on Home and Discover"],
        "accountSecurity": [.zh: "账号与安全", .ja: "アカウントと安全", .en: "Account and security"],
        "accountSecuritySubtitle": [.zh: "邮箱、密码、设备、黑名单和危险操作", .ja: "メール、パスワード、端末、ブロック、危険操作", .en: "Email, password, devices, blocklist, and dangerous actions"],
        "serviceGroup": [.zh: "服务", .ja: "サービス", .en: "Services"],
        "switchAccount": [.zh: "切换账号", .ja: "アカウント切替", .en: "Switch account"],
        "switchAccountSubtitle": [.zh: "选择另一个本地账号继续使用", .ja: "別のローカルアカウントを選択します", .en: "Use another local account"],
        "current": [.zh: "当前", .ja: "現在", .en: "Current"],
        "noAccounts": [.zh: "没有可切换账号", .ja: "切り替え可能なアカウントがありません", .en: "No accounts"],
        "noAccountsSubtitle": [.zh: "注册或导入账号后会显示在这里。", .ja: "登録またはインポートしたアカウントがここに表示されます。", .en: "Registered or imported accounts will appear here."],
        "logoutConfirm": [.zh: "是否退出账号？", .ja: "アカウントからログアウトしますか？", .en: "Log out of this account?"],
        "profileSubtitle": [.zh: "查看自己的投稿和资料", .ja: "投稿とプロフィールを確認", .en: "View your posts and profile"],
        "editProfileSubtitle": [.zh: "修改头像、封面、昵称和简介", .ja: "アイコン、カバー、名前、自己紹介を編集", .en: "Edit avatar, cover, name, and bio"],
        "accountPassword": [.zh: "账号与密码", .ja: "アカウントとパスワード", .en: "Account and password"],
        "accountPasswordSubtitle": [.zh: "修改用户名、邮箱和密码", .ja: "ユーザー名、メール、パスワードを変更", .en: "Change username, email, and password"],
        "contactInfo": [.zh: "邮箱与手机号", .ja: "メールと電話番号", .en: "Email and phone"],
        "contactSubtitle": [.zh: "管理联系邮箱和手机号", .ja: "連絡先メールと電話番号を管理", .en: "Manage email and phone"],
        "membership": [.zh: "会员与认证", .ja: "メンバーシップと認証", .en: "Membership and verification"],
        "verifiedAccount": [.zh: "已认证账号", .ja: "認証済みアカウント", .en: "Verified account"],
        "upgradeVerify": [.zh: "升级认证", .ja: "認証を申請", .en: "Apply for verification"],
        "defaultBio": [.zh: "还没有填写简介。", .ja: "プロフィールはまだありません。", .en: "No bio yet."],
        "joined": [.zh: "加入", .ja: "参加", .en: "joined"],
        "noContent": [.zh: "暂无内容", .ja: "コンテンツはありません", .en: "No content yet"],
        "emptyPosts": [.zh: "暂无投稿", .ja: "投稿はありません", .en: "No posts yet"],
        "emptyReplies": [.zh: "暂无回复", .ja: "返信はありません", .en: "No replies yet"],
        "emptyMedia": [.zh: "暂无媒体", .ja: "メディアはありません", .en: "No media yet"],
        "emptyLikes": [.zh: "暂无喜欢", .ja: "いいねはありません", .en: "No likes yet"],
        "shareProfile": [.zh: "分享主页", .ja: "プロフィールを共有", .en: "Share profile"],
        "reportUser": [.zh: "举报用户", .ja: "ユーザーを通報", .en: "Report user"],
        "blockUser": [.zh: "拉黑用户", .ja: "ユーザーをブロック", .en: "Block user"],
        "unblockUser": [.zh: "解除拉黑", .ja: "ブロック解除", .en: "Unblock"],
        "userBlocked": [.zh: "已拉黑该用户。", .ja: "ユーザーをブロックしました。", .en: "User blocked."],
        "userUnblocked": [.zh: "已解除拉黑。", .ja: "ブロックを解除しました。", .en: "User unblocked."],
        "blockedUsers": [.zh: "位已拉黑用户", .ja: "件のブロック", .en: "blocked users"],
        "emptyFollowingFeed": [.zh: "关注频道还没有内容", .ja: "フォロー中の投稿はまだありません", .en: "No following posts yet"],
        "emptyFollowingFeedHelp": [.zh: "关注一些用户后，这里会只显示他们的新内容。", .ja: "ユーザーをフォローすると、その投稿がここに表示されます。", .en: "Follow people to see only their posts here."],
        "cancel": [.zh: "取消", .ja: "キャンセル", .en: "Cancel"],
        "delete": [.zh: "删除", .ja: "削除", .en: "Delete"],
        "save": [.zh: "保存", .ja: "保存", .en: "Save"],
        "expand": [.zh: "展开", .ja: "展開", .en: "Expand"],
        "viewFullText": [.zh: "查看全文", .ja: "全文を表示", .en: "Read more"],
        "collapseText": [.zh: "收起", .ja: "閉じる", .en: "Collapse"],
        "editProfile": [.zh: "编辑资料", .ja: "プロフィール編集", .en: "Edit profile"],
        "follow": [.zh: "关注", .ja: "フォロー", .en: "Follow"],
        "followed": [.zh: "已关注", .ja: "フォロー中", .en: "Following"],
        "postDetails": [.zh: "帖子详情", .ja: "投稿詳細", .en: "Post details"],
        "postDeleted": [.zh: "帖子不存在或已删除", .ja: "投稿が存在しないか削除されました", .en: "Post not found or deleted"],
        "postDeletedHelp": [.zh: "可能是链接失效、内容已删除，或本地数据还没有同步。", .ja: "リンク切れ、削除済み、またはローカルデータが未同期の可能性があります。", .en: "The link may be stale, the post may have been removed, or local data may not be synced yet."],
        "discardDraftTitle": [.zh: "放弃这次编辑？", .ja: "この編集を破棄しますか？", .en: "Discard this draft?"],
        "discard": [.zh: "放弃", .ja: "破棄", .en: "Discard"],
        "keepEditing": [.zh: "继续编辑", .ja: "編集を続ける", .en: "Keep editing"],
        "mediaPreview": [.zh: "媒体预览", .ja: "メディアプレビュー", .en: "Media preview"],
        "processingMedia": [.zh: "正在处理媒体...", .ja: "メディアを処理中...", .en: "Processing media..."],
        "postingEllipsis": [.zh: "正在发布...", .ja: "投稿中...", .en: "Posting..."],
        "postingCompact": [.zh: "发布中", .ja: "投稿中", .en: "Posting"],
        "happeningNow": [.zh: "正在发生", .ja: "いま起きていること", .en: "Happening now"],
        "happeningSubtitle": [.zh: "新闻线索、社区讨论和话题动态。", .ja: "ニュース、コミュニティ、話題の動き。", .en: "News leads, community talk, and topic signals."],
        "topStory": [.zh: "焦点", .ja: "注目", .en: "Top story"],
        "untitledPost": [.zh: "一条新动态", .ja: "新しい投稿", .en: "New post"],
        "untitledTopic": [.zh: "新话题", .ja: "新しいトピック", .en: "New topic"],
        "searchPlaceholder": [.zh: "搜索帖子、用户、话题、城市、工作、租房、二手", .ja: "投稿、ユーザー、話題、都市、仕事、賃貸、中古を検索", .en: "Search posts, users, topics, cities, jobs, rentals, secondhand"],
        "searchPlaceholderShort": [.zh: "搜索帖子、用户、话题、城市", .ja: "投稿・ユーザー・話題・都市を検索", .en: "Search posts, users, topics, cities"],
        "contentLanguage": [.zh: "内容语言", .ja: "コンテンツ言語", .en: "Content language"],
        "contentLanguageSubtitle": [.zh: "决定推荐与热榜优先展示哪种语言的投稿", .ja: "おすすめ・ホットに優先表示する投稿の言語", .en: "Languages prioritized in recommendations and hot lists"],
        "contentLanguageFollowApp": [.zh: "跟随 App 语言", .ja: "アプリ言語に従う", .en: "Follow app language"],
        "contentLanguageMulti": [.zh: "多语言内容", .ja: "多言語コンテンツ", .en: "Multilingual"],
        "contentLanguagePrimary": [.zh: "首选语言", .ja: "優先言語", .en: "Primary"],
        "contentLanguageFallback": [.zh: "次选语言", .ja: "代替言語", .en: "Fallback"],
        "contentLanguageFallbackHint": [.zh: "当首选语言内容不足时,优先展示这些语言", .ja: "優先言語の投稿が少ない場合に表示する言語", .en: "Languages shown when there isn't enough primary-language content"],
        "cityPrimaryRecommend": [.zh: "推荐", .ja: "おすすめ", .en: "For you"],
        "cityPrimaryLife": [.zh: "生活", .ja: "生活", .en: "Life"],
        "cityPrimaryMarketplace": [.zh: "交易", .ja: "取引", .en: "Marketplace"],
        "cityPrimaryWork": [.zh: "工作", .ja: "仕事", .en: "Work"],
        "cityPrimarySocial": [.zh: "社交", .ja: "ソーシャル", .en: "Social"],
        "cityPrimaryInfo": [.zh: "资讯", .ja: "情報", .en: "Info"],
        "recentSearches": [.zh: "最近搜索", .ja: "最近の検索", .en: "Recent searches"],
        "clear": [.zh: "清空", .ja: "クリア", .en: "Clear"],
        "hotSearchRank": [.zh: "推荐内容", .ja: "おすすめコンテンツ", .en: "Recommended"],
        "newsRank": [.zh: "最新内容", .ja: "最新コンテンツ", .en: "Latest"],
        "recommendedFollow": [.zh: "推荐关注", .ja: "おすすめユーザー", .en: "Recommended follows"],
        "hotSearch": [.zh: "推荐", .ja: "おすすめ", .en: "Recommended"],
        "news": [.zh: "新闻", .ja: "ニュース", .en: "News"],
        "users": [.zh: "用户", .ja: "ユーザー", .en: "Users"],
        "noTopicPosts": [.zh: "暂无相关内容", .ja: "関連する投稿はありません", .en: "No related posts yet"],
        "profileCopied": [.zh: "主页账号已复制。", .ja: "プロフィールIDをコピーしました。", .en: "Profile handle copied."],
        "reportRecorded": [.zh: "举报已记录。", .ja: "通報を記録しました。", .en: "Report saved."],
        "login": [.zh: "登录", .ja: "ログイン", .en: "Log in"],
        "register": [.zh: "注册", .ja: "登録", .en: "Register"],
        "username": [.zh: "用户名", .ja: "ユーザー名", .en: "Username"],
        "displayName": [.zh: "显示名", .ja: "表示名", .en: "Display name"],
        "email": [.zh: "邮箱", .ja: "メール", .en: "Email"],
        "password": [.zh: "密码", .ja: "パスワード", .en: "Password"],
        "enterPassword": [.zh: "输入密码", .ja: "パスワードを入力", .en: "Enter password"],
        "passwordMin": [.zh: "至少 8 位，包含字母和数字", .ja: "8文字以上・英字と数字を含む", .en: "At least 8 characters with letters and numbers"],
        "loginKaiX": [.zh: "登录 Machi", .ja: "Machi にログイン", .en: "Log in to Machi"],
        "loginMachi": [.zh: "登录 Machi", .ja: "Machi にログイン", .en: "Log in to Machi"],
        "continueWithGoogle": [.zh: "使用 Google 登录", .ja: "Google で続ける", .en: "Continue with Google"],
        "googleSigningIn": [.zh: "正在打开 Google…", .ja: "Google を開いています…", .en: "Opening Google…"],
        "googleLoginFailed": [.zh: "Google 登录未完成，请稍后再试。", .ja: "Google ログインが完了しませんでした。もう一度お試しください。", .en: "Google sign-in was not completed. Please try again."],
        "appleLoginFailed": [.zh: "Apple 登录未完成，请稍后再试。", .ja: "Apple サインインが完了しませんでした。もう一度お試しください。", .en: "Sign in with Apple was not completed. Please try again."],
        // Guest browsing (App Store 5.1.1(v): browse before login)
        "browseAsGuest": [.zh: "先逛逛，看看城市内容", .ja: "ゲストとして街の投稿を見る", .en: "Browse city content first"],
        "guestModeBadge": [.zh: "游客浏览", .ja: "ゲスト閲覧", .en: "Guest"],
        "guestLoginRequired": [.zh: "登录后即可使用此功能", .ja: "この機能を使うにはログインが必要です", .en: "Log in to use this"],
        "guestProfileTitle": [.zh: "登录后解锁完整体验", .ja: "ログインして全機能を解放", .en: "Log in to unlock everything"],
        "guestProfileSubtitle": [.zh: "登录或注册后即可发布、收藏、私信、开通会员，并在多设备同步。", .ja: "ログイン / 登録すると、投稿・保存・メッセージ・会員機能をマルチデバイスで利用できます。", .en: "Log in or sign up to post, save, message, go Verified, and sync across devices."],
        "loginOrRegister": [.zh: "登录 / 注册", .ja: "ログイン / 登録", .en: "Log in / Sign up"],
        "localDatabaseOnline": [.zh: "Machi 在线", .ja: "Machi オンライン", .en: "Machi online"],
        "welcomeBack": [.zh: "在每一座城市，找到生活的回声。", .ja: "どの街でも、暮らしの声が見つかる。", .en: "Find the pulse of everyday life in every city."],
        "logoutConfirmMessage": [.zh: "退出后需要重新登录才能使用发布、私信、收藏和会员等功能。", .ja: "ログアウト後、投稿・メッセージ・保存・会員機能を使うには再ログインが必要です。", .en: "After logging out, you will need to sign in again to post, message, save, and use membership features."],
        "mutualFriendsOnly": [.zh: "互相关注后，就可以从这里开始新的私信。", .ja: "相互フォローすると、ここから新しいメッセージを始められます。", .en: "Mutual follows can start a new message here."],
        "mutualFriendBadge": [.zh: "互关好友", .ja: "相互フォロー", .en: "Mutual friend"],
        "countryScopeValue": [.zh: "国家", .ja: "国", .en: "Country"],
        "countryScope": [.zh: "内容范围", .ja: "表示範囲", .en: "Content scope"],
        "cityScopeValue": [.zh: "城市", .ja: "都市", .en: "City"],
        "cityScope": [.zh: "本地频道", .ja: "ローカル欄", .en: "Local channels"],
        "lifeInfoValue": [.zh: "生活", .ja: "暮らし", .en: "Life"],
        "lifeInfo": [.zh: "实用信息", .ja: "実用情報", .en: "Useful info"],
        "liveChannels": [.zh: "本地频道", .ja: "ローカル欄", .en: "Local channels"],
        "localPersistence": [.zh: "内容范围", .ja: "表示範囲", .en: "Content scope"],
        "portableArchitecture": [.zh: "实用信息", .ja: "実用情報", .en: "Useful info"],
        "interaction": [.zh: "互动", .ja: "交流", .en: "Interaction"],
        "registerRegion": [.zh: "注册地区", .ja: "登録地域", .en: "Registration region"],
        "selectRegisterRegion": [.zh: "选择国家和城市", .ja: "国と都市を選ぶ", .en: "Choose country and city"],
        "registerRegionHelp": [.zh: "注册后优先显示 {country} 内容", .ja: "登録後は {country} の内容を優先表示", .en: "After signup, Machi shows {country} content"],
        "selectRegisterRegionError": [.zh: "请选择注册国家和城市。", .ja: "登録する国と都市を選んでください。", .en: "Choose a country and city to register."],
        "availableCities": [.zh: "可选城市", .ja: "選べる都市", .en: "Available cities"],
        "housing": [.zh: "租房", .ja: "住まい", .en: "Housing"],
        "work": [.zh: "工作", .ja: "仕事", .en: "Work"],
        "secondhand": [.zh: "二手", .ja: "中古", .en: "Secondhand"],
        "events": [.zh: "活动", .ja: "イベント", .en: "Events"],
        "createAccount": [.zh: "创建账号", .ja: "アカウント作成", .en: "Create account"],
        "wrongCredentials": [.zh: "账号或密码不正确。", .ja: "ユーザー名またはパスワードが違います。", .en: "Username or password is incorrect."],
        "handleTaken": [.zh: "这个用户名已经被使用。", .ja: "このユーザー名は使用されています。", .en: "This username is already taken."],
        "passwordTooShort": [.zh: "密码至少 8 位，并包含字母和数字。", .ja: "パスワードは8文字以上で、英字と数字を含めてください。", .en: "Password must be at least 8 characters and include letters and numbers."],
        "authUsernameRequired": [.zh: "请输入用户名。", .ja: "ユーザー名を入力してください。", .en: "Enter a username."],
        "authPasswordRequired": [.zh: "请输入密码。", .ja: "パスワードを入力してください。", .en: "Enter a password."],
        "authInvalidHandle": [.zh: "用户名只能用小写字母、数字、下划线和点，3–20 位，且不能使用官方保留名。", .ja: "ユーザー名は小文字英数字、アンダースコア、ドットのみ、3〜20文字です。公式予約名は使えません。", .en: "Use 3-20 lowercase letters, numbers, underscores, or dots. Reserved official names are unavailable."],
        "authDisplayNameRequired": [.zh: "请填写显示名称。", .ja: "表示名を入力してください。", .en: "Enter a display name."],
        "authDisplayNameTooLong": [.zh: "显示名称不超过 32 个字。", .ja: "表示名は32文字以内です。", .en: "Display name must be 32 characters or fewer."],
        "authInvalidEmail": [.zh: "邮箱格式不正确。", .ja: "メール形式が正しくありません。", .en: "Enter a valid email address."],
        "authEmailTaken": [.zh: "这个邮箱已被注册过。", .ja: "このメールは登録済みです。", .en: "This email is already registered."],
        "authEmailRequired": [.zh: "请输入邮箱。", .ja: "メールアドレスを入力してください。", .en: "Email is required."],
        "authVerificationCode": [.zh: "邮箱验证码", .ja: "認証コード", .en: "Email code"],
        "authSendCode": [.zh: "发送验证码", .ja: "コードを送信", .en: "Send code"],
        "authResendCode": [.zh: "重新发送", .ja: "再送信", .en: "Resend"],
        "authCodeSent": [.zh: "验证码已发送，请查收邮箱。", .ja: "コードを送信しました。メールをご確認ください。", .en: "Code sent — check your email."],
        "authCodeRequired": [.zh: "请输入邮箱验证码。", .ja: "認証コードを入力してください。", .en: "Enter the email code."],
        "authCodeInvalid": [.zh: "验证码无效或已过期。", .ja: "コードが無効または期限切れです。", .en: "Code is invalid or expired."],
        "authCaptcha": [.zh: "图形验证码", .ja: "画像認証", .en: "Captcha"],
        "authCaptchaPlaceholder": [.zh: "输入图中字符", .ja: "画像の文字を入力", .en: "Enter the characters"],
        "authCaptchaRequired": [.zh: "请输入图形验证码。", .ja: "画像認証コードを入力してください。", .en: "Enter the captcha characters."],
        "authCaptchaInvalid": [.zh: "图形验证码不正确，请重试。", .ja: "画像認証コードが正しくありません。", .en: "The captcha is incorrect. Try again."],
        "authCaptchaRefreshHint": [.zh: "点图片刷新", .ja: "画像タップで更新", .en: "Tap image to refresh"],
        "authCaptchaLoadFailed": [.zh: "加载失败，点按重试", .ja: "読み込み失敗・タップで再試行", .en: "Load failed — tap to retry"],
        "authChecking": [.zh: "检查中…", .ja: "確認中…", .en: "Checking…"],
        "authUsernameAvailable": [.zh: "用户名可用", .ja: "利用可能なユーザー名", .en: "Username available"],
        "authEmailAvailable": [.zh: "邮箱可用", .ja: "利用可能なメール", .en: "Email available"],
        "authUserNotFound": [.zh: "用户名不存在，要不要先注册一个？", .ja: "ユーザーが見つかりません。先に登録しますか？", .en: "Username not found. Create an account first?"],
        "authRateLimited": [.zh: "尝试过多，请稍等 30 秒后再试。", .ja: "試行回数が多すぎます。30秒後に再試行してください。", .en: "Too many attempts. Try again in 30 seconds."],
        "authNetworkError": [.zh: "无法连接服务器，请检查网络后重试。", .ja: "サーバーに接続できません。ネットワークを確認してください。", .en: "Cannot connect to the server. Check your network and try again."],
        "authTimeout": [.zh: "请求超时，请稍后再试。", .ja: "リクエストがタイムアウトしました。後でもう一度お試しください。", .en: "Request timed out. Try again later."],
        "databaseSaveFailed": [.zh: "数据库保存失败，请重试。", .ja: "保存に失敗しました。もう一度お試しください。", .en: "Database save failed. Please try again."],
        "forYou": [.zh: "推荐", .ja: "おすすめ", .en: "For You"],
        "local": [.zh: "同城", .ja: "地元", .en: "Local"],
        "following": [.zh: "关注", .ja: "フォロー中", .en: "Following"],
        "hot": [.zh: "热榜", .ja: "急上昇", .en: "Hot"],
        "cityChannel": [.zh: "城市频道", .ja: "都市チャンネル", .en: "City channel"],
        "pickRegion": [.zh: "选择城市", .ja: "都市を選ぶ", .en: "Pick a city"],
        "pickRegionPrompt": [.zh: "选个城市,看看你身边的人在聊什么。", .ja: "都市を選んで、地元の人の話題を見よう。", .en: "Choose a city to see what locals are talking about."],
        "currentRegion": [.zh: "当前城市", .ja: "現在の都市", .en: "Current city"],
        "switchCountry": [.zh: "切换国家", .ja: "国を切り替える", .en: "Switch country"],
        "switchLocalRegion": [.zh: "切换本国城市和地区", .ja: "この国の都市・地域を切り替える", .en: "Switch cities and regions in this country"],
        "regionNoMatches": [.zh: "没有匹配的地区", .ja: "一致する地域がありません", .en: "No matching regions"],
        "currentRegionSubtitle": [.zh: "只影响首页和推荐流，不会修改我的地区", .ja: "ホームとおすすめのみ変更し、プロフィール地域は変えません", .en: "Affects home and recommendations, not your profile region"],
        "profileRegion": [.zh: "我的地区", .ja: "プロフィール地域", .en: "My region"],
        "profileRegionSubtitle": [.zh: "显示在个人资料中，不会自动切换首页城市", .ja: "プロフィールに表示され、ホーム都市は自動変更しません", .en: "Shown on your profile; does not switch home city automatically"],
        "profileRegionHelp": [.zh: "这里是个人资料中的地区。修改后不会强制切换首页当前浏览城市。", .ja: "プロフィール上の地域です。変更してもホームの閲覧都市は切り替わりません。", .en: "This is your profile region. Changing it will not switch the current browsing city."],
        "profileRegionUpdated": [.zh: "我的地区已更新。", .ja: "プロフィール地域を更新しました。", .en: "Profile region updated."],
        "popularCities": [.zh: "热门城市", .ja: "人気の都市", .en: "Popular cities"],
        "recentRegions": [.zh: "最近选择", .ja: "最近の選択", .en: "Recent"],
        "searchRegion": [.zh: "搜索国家、省份、城市", .ja: "国・地域・都市を検索", .en: "Search country, province, city"],
        "allCountries": [.zh: "全部国家", .ja: "国を選ぶ", .en: "All countries"],
        "selectCountry": [.zh: "选择国家", .ja: "国を選ぶ", .en: "Select country"],
        "selectProvince": [.zh: "选择省 / 州", .ja: "都道府県・州を選ぶ", .en: "Select province / state"],
        "selectCity": [.zh: "选择城市", .ja: "都市を選ぶ", .en: "Select city"],
        // ---- Content types (phase 2) ----
        "ct_picker_title":   [.zh: "选个内容类型", .ja: "投稿タイプを選ぶ", .en: "Pick a content type"],
        "ct_picker_sub":     [.zh: "不同类型的帖子会进不同的频道", .ja: "タイプによって表示先が変わります", .en: "Different types route to different channels"],
        "ct_picker_common":  [.zh: "常用类型", .ja: "よく使うタイプ", .en: "Common types"],
        "ct_picker_recent":  [.zh: "最近使用", .ja: "最近使用", .en: "Recently used"],
        "ct_picker_more":    [.zh: "更多类型", .ja: "もっと見る", .en: "More types"],
        "ct_picker_search":  [.zh: "搜索类型", .ja: "タイプを検索", .en: "Search types"],
        "ct_picker_noResult":[.zh: "没有匹配的类型", .ja: "一致するタイプがありません", .en: "No matching types"],
        "composeMissingHeader":[.zh: "还差几个必填项就可以发布了", .ja: "あと少しで公開できます", .en: "A few required fields left"],
        "composePublishFailed":[.zh: "发布失败,请稍后再试", .ja: "投稿に失敗しました", .en: "Failed to publish, try again"],
        "composeDraftSaved":   [.zh: "已存为草稿", .ja: "下書きに保存", .en: "Saved as draft"],
        "contactSeller":       [.zh: "私信咨询", .ja: "問い合わせる", .en: "Send a message"],
        "inquireOrApply":      [.zh: "私信报名", .ja: "応募する", .en: "Apply"],
        "ct_dynamic":        [.zh: "动态",   .ja: "つぶやき", .en: "Post"],
        "ct_dynamic_sub":    [.zh: "聊聊近况", .ja: "近況を共有", .en: "Share what's up"],
        "ct_image":          [.zh: "图文",   .ja: "写真",    .en: "Photo"],
        "ct_image_sub":      [.zh: "图片为主", .ja: "写真がメイン", .en: "Photo-led"],
        "ct_long":           [.zh: "长文",   .ja: "長文",    .en: "Long post"],
        "ct_long_sub":       [.zh: "适合写心得", .ja: "じっくり書く", .en: "Write at length"],
        "ct_news":           [.zh: "新闻",   .ja: "ニュース", .en: "News"],
        "ct_news_sub":       [.zh: "本地新闻和快讯", .ja: "地元ニュース", .en: "Local news"],
        "ct_localinfo":      [.zh: "本地告示", .ja: "地元のお知らせ", .en: "Local notice"],
        "ct_localinfo_sub":  [.zh: "停水停电 / 社区通知", .ja: "停止・社区通知", .en: "Outages / notices"],
        "ct_guide":          [.zh: "攻略",   .ja: "ガイド",  .en: "Guide"],
        "ct_guide_sub":      [.zh: "省时省钱经验", .ja: "新参者向けのコツ", .en: "Save-time tips"],
        "ct_question":       [.zh: "提问",   .ja: "質問",   .en: "Question"],
        "ct_question_sub":   [.zh: "请教本地朋友", .ja: "地元の方に聞く", .en: "Ask locals"],
        "ct_rant":           [.zh: "吐槽",   .ja: "愚痴",   .en: "Rant"],
        "ct_rant_sub":       [.zh: "找个地方说出来", .ja: "ぼやきの場所", .en: "Vent here"],
        "ct_secondhand":     [.zh: "二手",   .ja: "中古",   .en: "Secondhand"],
        "ct_secondhand_sub": [.zh: "买卖闲置", .ja: "売り買い", .en: "Buy / sell used"],
        "ct_housing":        [.zh: "租房",   .ja: "賃貸",   .en: "Housing"],
        "ct_housing_sub":    [.zh: "找房、转租、房源分享", .ja: "賃貸・サブリース", .en: "Rentals / sublets"],
        "ct_roommate":       [.zh: "找室友", .ja: "ルームメイト", .en: "Roommate"],
        "ct_roommate_sub":   [.zh: "招室友、找合租", .ja: "ルームメイト募集", .en: "Find roommates"],
        "ct_jobseek":        [.zh: "找工作", .ja: "求職",   .en: "Job seek"],
        "ct_jobseek_sub":    [.zh: "求职、简历分享", .ja: "求職・履歴書", .en: "Job hunting"],
        "ct_jobpost":        [.zh: "招聘",   .ja: "求人",   .en: "Job post"],
        "ct_jobpost_sub":    [.zh: "公司/商家招聘", .ja: "求人募集", .en: "Hiring"],
        "ct_referral":       [.zh: "内推",   .ja: "リファラル", .en: "Referral"],
        "ct_referral_sub":   [.zh: "内推机会", .ja: "リファラル機会", .en: "Referral spots"],
        "ct_meetup":         [.zh: "小组",   .ja: "地域グループ", .en: "Groups"],
        "ct_meetup_sub":     [.zh: "学习、运动、语言交换", .ja: "学習・運動・言語交換", .en: "Study, sports, language exchange"],
        "ct_dining":         [.zh: "美食",   .ja: "食事",  .en: "Dining"],
        "ct_dining_sub":     [.zh: "美食、探店、咖啡", .ja: "食事・カフェ", .en: "Food meetups & cafés"],
        "ct_event":          [.zh: "活动",   .ja: "イベント", .en: "Event"],
        "ct_event_sub":      [.zh: "聚会、展览、桌游", .ja: "オフ会・展示", .en: "Meetups & shows"],
        "ct_service":        [.zh: "服务",   .ja: "サービス", .en: "Service"],
        "ct_service_sub":    [.zh: "搬家、翻译、签证", .ja: "引越・翻訳・ビザ", .en: "Moving / translation"],
        "ct_merchant":       [.zh: "商家",   .ja: "店舗",   .en: "Merchant"],
        "ct_merchant_sub":   [.zh: "本地店铺", .ja: "地元店舗", .en: "Local shops"],
        "ct_coupon":         [.zh: "优惠",   .ja: "クーポン", .en: "Deals"],
        "ct_coupon_sub":     [.zh: "折扣团购优惠券", .ja: "割引・クーポン", .en: "Discounts"],
        "ct_warning":        [.zh: "避坑",   .ja: "注意喚起", .en: "Warning"],
        "ct_warning_sub":    [.zh: "防骗、避坑、经验分享", .ja: "詐欺・トラブル防止", .en: "Avoid scams"],
        "ct_poll":           [.zh: "投票",   .ja: "投票",   .en: "Poll"],
        "ct_poll_sub":       [.zh: "发起投票", .ja: "投票を作る", .en: "Run a poll"],
        "ct_anonymous":      [.zh: "树洞",   .ja: "匿名",   .en: "Anonymous"],
        "ct_anonymous_sub":  [.zh: "匿名发言", .ja: "匿名投稿", .en: "Post anonymously"],
        // typed-form field labels
        "fld_title":         [.zh: "标题",   .ja: "タイトル", .en: "Title"],
        "fld_price":         [.zh: "价格",   .ja: "価格",   .en: "Price"],
        "fld_currency":      [.zh: "货币",   .ja: "通貨",   .en: "Currency"],
        "fld_condition":     [.zh: "成色",   .ja: "状態",   .en: "Condition"],
        "fld_trade_method":  [.zh: "交易方式", .ja: "取引方法", .en: "Trade method"],
        "fld_area":          [.zh: "区域",   .ja: "エリア", .en: "Area"],
        "fld_category":      [.zh: "分类",   .ja: "カテゴリ", .en: "Category"],
        "fld_rent":          [.zh: "租金",   .ja: "家賃",   .en: "Rent"],
        "fld_rent_range":    [.zh: "租金范围", .ja: "家賃範囲", .en: "Rent range"],
        "fld_room_type":     [.zh: "户型",   .ja: "間取り", .en: "Room type"],
        "fld_nearest_station":[.zh: "最近车站", .ja: "最寄駅", .en: "Nearest station"],
        "fld_move_in_date":  [.zh: "入住日期", .ja: "入居日", .en: "Move-in date"],
        "fld_deposit":       [.zh: "押金",   .ja: "敷金",   .en: "Deposit"],
        "fld_key_money":     [.zh: "礼金",   .ja: "礼金",   .en: "Key money"],
        "fld_contact_method":[.zh: "联系方式", .ja: "連絡先", .en: "Contact"],
        "fld_lifestyle_tags":[.zh: "生活习惯", .ja: "生活タグ", .en: "Lifestyle tags"],
        "fld_requirements":  [.zh: "要求",   .ja: "条件",   .en: "Requirements"],
        "fld_desired_job":   [.zh: "求职方向", .ja: "希望職種", .en: "Desired job"],
        "fld_skills":        [.zh: "技能",   .ja: "スキル", .en: "Skills"],
        "fld_languages":     [.zh: "语言能力", .ja: "言語", .en: "Languages"],
        "fld_visa_status":   [.zh: "签证状态", .ja: "ビザ状況", .en: "Visa status"],
        "fld_availability":  [.zh: "可开始时间", .ja: "開始可能時期", .en: "Availability"],
        "fld_expected_salary":[.zh: "期望薪资", .ja: "希望給与", .en: "Expected salary"],
        "fld_resume_url":    [.zh: "简历链接", .ja: "履歴書URL", .en: "Resume URL"],
        "fld_job_title":     [.zh: "职位",   .ja: "ポジション", .en: "Job title"],
        "fld_company_name":  [.zh: "公司",   .ja: "会社名", .en: "Company"],
        "fld_salary":        [.zh: "薪资",   .ja: "給与",   .en: "Salary"],
        "fld_job_type":      [.zh: "工作类型", .ja: "雇用形態", .en: "Job type"],
        "fld_language_req":  [.zh: "语言要求", .ja: "言語要件", .en: "Language requirements"],
        "fld_visa_req":      [.zh: "签证要求", .ja: "ビザ要件", .en: "Visa requirements"],
        "fld_work_location": [.zh: "工作地点", .ja: "勤務地", .en: "Work location"],
        "fld_meetup_type":   [.zh: "类型",   .ja: "種類",   .en: "Type"],
        "fld_meetup_time":   [.zh: "时间",   .ja: "時間",   .en: "Time"],
        "fld_location":      [.zh: "地点",   .ja: "場所",   .en: "Location"],
        "fld_people_limit":  [.zh: "人数上限", .ja: "人数",   .en: "Capacity"],
        "fld_budget":        [.zh: "预算",   .ja: "予算",   .en: "Budget"],
        "fld_description":   [.zh: "描述",   .ja: "詳細",   .en: "Description"],
        "fld_question":      [.zh: "问题",   .ja: "質問",   .en: "Question"],
        "fld_summary":       [.zh: "摘要",   .ja: "概要",   .en: "Summary"],
        "fld_source":        [.zh: "来源",   .ja: "出典",   .en: "Source"],
        "fld_external_url":  [.zh: "外部链接", .ja: "外部URL", .en: "External URL"],
        "fld_cover_image":   [.zh: "封面链接", .ja: "カバー画像", .en: "Cover image"],
        "fld_last_updated":  [.zh: "最后更新", .ja: "最終更新", .en: "Last updated"],
        "fld_restaurant_or_area":[.zh: "餐厅 / 区域", .ja: "店・エリア", .en: "Restaurant / area"],
        "fld_service_type":  [.zh: "服务类型", .ja: "サービス種別", .en: "Service type"],
        "fld_price_range":   [.zh: "价格范围", .ja: "価格帯", .en: "Price range"],
        "fld_merchant_id":   [.zh: "商家 ID", .ja: "店舗ID", .en: "Merchant ID"],
        "fld_verified_status":[.zh: "认证状态", .ja: "認証状態", .en: "Verified status"],
        "fld_merchant_name": [.zh: "商家名称", .ja: "店舗名", .en: "Merchant name"],
        "fld_merchant_type": [.zh: "商家类型", .ja: "店舗種別", .en: "Merchant type"],
        "fld_address":       [.zh: "地址",   .ja: "住所",   .en: "Address"],
        "fld_opening_hours": [.zh: "营业时间", .ja: "営業時間", .en: "Opening hours"],
        "fld_rating":        [.zh: "评分",   .ja: "評価",   .en: "Rating"],
        "fld_discount_info": [.zh: "优惠信息", .ja: "割引内容", .en: "Discount info"],
        "fld_valid_until":   [.zh: "有效期", .ja: "有効期限", .en: "Valid until"],
        "fld_usage_rules":   [.zh: "使用规则", .ja: "利用条件", .en: "Usage rules"],
        "fld_evidence_images":[.zh: "证据图片链接", .ja: "証拠画像URL", .en: "Evidence image URLs"],
        "fld_anonymous":     [.zh: "匿名发布", .ja: "匿名で投稿", .en: "Post anonymously"],
        "fld_review_status": [.zh: "审核状态", .ja: "審査状態", .en: "Review status"],
        "fld_poll_options":  [.zh: "投票选项", .ja: "投票項目", .en: "Poll options"],
        "fld_expires_at":    [.zh: "截止时间", .ja: "締切",   .en: "Expires at"],
        "fld_event_time":    [.zh: "活动时间", .ja: "開催日時", .en: "Event time"],
        "fld_fee":           [.zh: "费用",   .ja: "参加費", .en: "Fee"],
        "fld_capacity":      [.zh: "容量",   .ja: "定員",   .en: "Capacity"],
        "fld_registration":  [.zh: "报名方式", .ja: "申込方法", .en: "Registration"],
        "safetyNotice":      [.zh: "安全提醒", .ja: "安全メモ", .en: "Safety note"],
        "companyVerified":   [.zh: "企业已认证", .ja: "企業認証済み", .en: "Company verified"],
        "fld_status":        [.zh: "状态",   .ja: "ステータス", .en: "Status"],
        "status_available":  [.zh: "可售",   .ja: "販売中", .en: "Available"],
        "status_reserved":   [.zh: "已预约", .ja: "予約済", .en: "Reserved"],
        "status_sold":       [.zh: "已售",   .ja: "売却済", .en: "Sold"],
        "status_rented":     [.zh: "已出租", .ja: "成約済", .en: "Rented"],
        "status_under_review":[.zh: "待审核", .ja: "審査中", .en: "Under review"],
        "status_active":     [.zh: "公开",   .ja: "公開",   .en: "Active"],
        "jt_full_time":      [.zh: "全职",   .ja: "正社員", .en: "Full-time"],
        "jt_part_time":      [.zh: "兼职",   .ja: "アルバイト", .en: "Part-time"],
        "jt_internship":     [.zh: "实习",   .ja: "インターン", .en: "Internship"],
        "jt_remote":         [.zh: "远程",   .ja: "リモート", .en: "Remote"],
        "compose": [.zh: "发布", .ja: "投稿", .en: "Compose"],
        "publish": [.zh: "发布", .ja: "投稿", .en: "Post"],
        "placeholderPost": [.zh: "有什么新鲜事？", .ja: "いま何が起きていますか？", .en: "What's happening?"],
        "addTopicPlaceholder": [.zh: "添加标签", .ja: "タグを追加", .en: "Add tag"],
        "recommendedTopics": [.zh: "随机推荐标签", .ja: "おすすめタグ", .en: "Suggested tags"],
        "addMedia": [.zh: "添加图片或视频", .ja: "画像または動画を追加", .en: "Add photo or video"],
        "posting": [.zh: "正在发布", .ja: "投稿中", .en: "Posting"],
        "posted": [.zh: "已发布", .ja: "投稿しました", .en: "Posted"],
        "failedToPost": [.zh: "发布失败", .ja: "投稿に失敗しました", .en: "Failed to post"],
        "retry": [.zh: "重试", .ja: "再試行", .en: "Retry"],
        "emptyFeed": [.zh: "暂无帖子", .ja: "投稿はありません", .en: "No posts yet"],
        "emptyFeedHelp": [.zh: "发布第一条内容，或稍后重试加载。", .ja: "最初の投稿を作成するか、後でもう一度お試しください。", .en: "Create the first post or try loading again later."],
        "loading": [.zh: "加载中", .ja: "読み込み中", .en: "Loading"],
        "error": [.zh: "出现错误", .ja: "エラーが発生しました", .en: "Something went wrong"],
        "comments": [.zh: "评论", .ja: "コメント", .en: "Comments"],
        "writeComment": [.zh: "写评论", .ja: "コメントを書く", .en: "Write a comment"],
        "noComments": [.zh: "还没有评论", .ja: "コメントはまだありません", .en: "No comments yet"],
        "commentSyncError": [.zh: "评论数据正在同步，请重试。", .ja: "コメントを同期中です。もう一度お試しください。", .en: "Comments are syncing. Please try again."],
        "reply": [.zh: "回复", .ja: "返信", .en: "Reply"],
        "latest": [.zh: "最新", .ja: "最新", .en: "Latest"],
        "top": [.zh: "高赞", .ja: "人気", .en: "Top"],
        "like": [.zh: "喜欢", .ja: "いいね", .en: "Like"],
        "bookmark": [.zh: "收藏", .ja: "保存", .en: "Bookmark"],
        "repost": [.zh: "转发", .ja: "リポスト", .en: "Repost"],
        "undoRepost": [.zh: "取消转发", .ja: "リポストを取り消す", .en: "Undo repost"],
        "quotePost": [.zh: "引用帖子", .ja: "引用リポスト", .en: "Quote post"],
        "quotePlaceholder": [.zh: "添加你的看法", .ja: "コメントを追加", .en: "Add your comment"],
        "repostedBy": [.zh: "转发了", .ja: "がリポストしました", .en: "reposted"],
        "editPost": [.zh: "编辑帖子", .ja: "投稿を編集", .en: "Edit post"],
        "deletePost": [.zh: "删除帖子", .ja: "投稿を削除", .en: "Delete post"],
        "deletePostConfirm": [.zh: "删除后这条帖子、评论、媒体和相关通知会从本机移除，无法撤销。", .ja: "削除すると、この投稿、コメント、メディア、関連通知がこの端末から削除され、元に戻せません。", .en: "This removes the post, comments, media, and related notifications from this device. This cannot be undone."],
        "postDeletedDone": [.zh: "帖子已删除。", .ja: "投稿を削除しました。", .en: "Post deleted."],
        "postOwnerTools": [.zh: "作者工具", .ja: "投稿者ツール", .en: "Author tools"],
        "postActions": [.zh: "帖子操作", .ja: "投稿操作", .en: "Post actions"],
        "reportPost": [.zh: "举报帖子", .ja: "投稿を通報", .en: "Report post"],
        "reportComment": [.zh: "举报评论", .ja: "コメントを通報", .en: "Report comment"],
        "sharePost": [.zh: "分享帖子", .ja: "投稿を共有", .en: "Share post"],
        "copyLink": [.zh: "复制链接", .ja: "リンクをコピー", .en: "Copy link"],
        "linkCopied": [.zh: "链接已复制。", .ja: "リンクをコピーしました。", .en: "Link copied."],
        "shareLinkReady": [.zh: "分享链接已复制。", .ja: "共有リンクをコピーしました。", .en: "Share link copied."],
        "postUpdated": [.zh: "帖子已更新。", .ja: "投稿を更新しました。", .en: "Post updated."],
        "views": [.zh: "浏览", .ja: "表示", .en: "views"],
        "heat": [.zh: "热度", .ja: "ヒート", .en: "Heat"],
        "topics": [.zh: "话题", .ja: "トピック", .en: "Topics"],
        "trending": [.zh: "热榜", .ja: "トレンド", .en: "Trending"],
        "emptySearch": [.zh: "没有找到内容", .ja: "結果がありません", .en: "No results"],
        "emptyNotifications": [.zh: "暂无通知", .ja: "通知はありません", .en: "No notifications"],
        "emptyMessages": [.zh: "暂无私信", .ja: "メッセージはありません", .en: "No messages"],
        "messagePlaceholder": [.zh: "输入消息", .ja: "メッセージを入力", .en: "Message"],
        "deleteConversation": [.zh: "删除会话", .ja: "会話を削除", .en: "Delete conversation"],
        "send": [.zh: "发送", .ja: "送信", .en: "Send"],
        "sent": [.zh: "已发送", .ja: "送信済み", .en: "Sent"],
        "sendFailed": [.zh: "发送失败", .ja: "送信失敗", .en: "Failed"],
        "posts": [.zh: "帖子", .ja: "投稿", .en: "Posts"],
        "likes": [.zh: "喜欢", .ja: "いいね", .en: "Likes"],
        "bookmarks": [.zh: "收藏", .ja: "保存", .en: "Bookmarks"],
        "media": [.zh: "媒体", .ja: "メディア", .en: "Media"],
        "followers": [.zh: "粉丝", .ja: "フォロワー", .en: "Followers"],
        "followingCount": [.zh: "关注", .ja: "フォロー", .en: "Following"],
        "totalHeat": [.zh: "总热度", .ja: "総ヒート", .en: "Total heat"],
        "savedByOthers": [.zh: "被收藏", .ja: "保存数", .en: "Saved"],
        "merchantVerified": [.zh: "商家认证", .ja: "店舗認証", .en: "Merchant verified"],
        "merchantPending":  [.zh: "商家待审核", .ja: "店舗審査中", .en: "Merchant pending"],
        "becomeMerchant":   [.zh: "申请商家认证", .ja: "店舗認証を申請", .en: "Apply for merchant verification"],
        "boostPost":        [.zh: "加热帖子", .ja: "ブースト", .en: "Boost post"],
        "boostedBadge":     [.zh: "已加热", .ja: "ブースト中", .en: "Boosted"],
        "regionSettings":   [.zh: "地区设置", .ja: "地域設定", .en: "Region settings"],
        "changeRegion":     [.zh: "切换地区", .ja: "地域を変更", .en: "Change region"],
        "hotScopeAll":      [.zh: "全站", .ja: "全体", .en: "All"],
        "hotScopeCountry":  [.zh: "国家", .ja: "国別", .en: "Country"],
        "hotScopeCity":     [.zh: "城市", .ja: "都市", .en: "City"],
        "merchantStatus":   [.zh: "认证状态", .ja: "認証ステータス", .en: "Verification status"],
        "merchantStatusVerified":[.zh: "已通过商家认证,可发布商家专属内容", .ja: "認証済み", .en: "Verified merchant"],
        "merchantStatusNone":[.zh: "你还不是商家,认证后可发布商家、优惠、服务等内容", .ja: "店舗認証を申請してください", .en: "Apply to publish merchant content"],
        "merchantApplyFooter":[.zh: "提交后会进入人工审核,通常 1-3 个工作日内回复。", .ja: "申請後、1〜3営業日以内に審査結果をご連絡します。", .en: "We'll review your application within 1-3 business days."],
        "followersList": [.zh: "粉丝", .ja: "フォロワー", .en: "Followers"],
        "followingList": [.zh: "正在关注", .ja: "フォロー中", .en: "Following"],
        "emptyFollowers": [.zh: "还没有粉丝", .ja: "フォロワーはまだいません", .en: "No followers yet"],
        "emptyFollowing": [.zh: "还没有关注任何人", .ja: "まだ誰もフォローしていません", .en: "Not following anyone yet"],
        "unknownUser": [.zh: "未知用户", .ja: "不明なユーザー", .en: "Unknown user"],
        "permissionDenied": [.zh: "没有相册权限，无法读取媒体。", .ja: "写真ライブラリの権限がありません。", .en: "Photo library permission is denied."],
        "mediaFailed": [.zh: "媒体处理失败，请换一个文件重试。", .ja: "メディア処理に失敗しました。別のファイルでお試しください。", .en: "Media processing failed. Try another file."],
        "mediaMixNotAllowed": [.zh: "图片和视频不能混合发布。", .ja: "画像と動画は同時に添付できません。", .en: "Photos and video cannot be mixed."],
        "mediaImageLimit": [.zh: "最多上传 9 张图片。", .ja: "画像は最大9枚までです。", .en: "You can upload up to 9 photos."],
        "mediaVideoLimit": [.zh: "最多上传 1 个视频。", .ja: "動画は最大1本までです。", .en: "You can upload up to 1 video."],
        "mediaVideoOnlyOne": [.zh: "只能添加 1 个视频，视频不能和图片一起发布。", .ja: "動画は1本のみ追加できます。画像とは同時に添付できません。", .en: "You can add only one video, and it cannot be mixed with photos."],
        "mediaUploadFailed": [.zh: "媒体上传失败", .ja: "メディアのアップロードに失敗しました", .en: "Media upload failed"],
        "mediaTooLarge": [.zh: "媒体文件超过当前类型的大小限制。", .ja: "メディアファイルがサイズ上限を超えています。", .en: "This media file exceeds the size limit."],
        "markAllRead": [.zh: "全部已读", .ja: "すべて既読", .en: "Mark all read"],
        "markRead": [.zh: "标记已读", .ja: "既読にする", .en: "Mark read"],
        "markUnread": [.zh: "标记未读", .ja: "未読にする", .en: "Mark unread"],
        "markViewed": [.zh: "已查看", .ja: "確認済み", .en: "Viewed"],
        "notifLiked": [.zh: "喜欢了你的帖子", .ja: "があなたの投稿にいいねしました", .en: "liked your post"],
        "notifReposted": [.zh: "转发了你的帖子", .ja: "があなたの投稿をリポストしました", .en: "reposted your post"],
        "notifCommented": [.zh: "评论了你的帖子", .ja: "があなたの投稿にコメントしました", .en: "commented on your post"],
        "notifReplied": [.zh: "回复了你", .ja: "があなたに返信しました", .en: "replied to you"],
        "notifMentioned": [.zh: "提到了你", .ja: "があなたをメンションしました", .en: "mentioned you"],
        "notifFollowed": [.zh: "关注了你", .ja: "があなたをフォローしました", .en: "followed you"],
        "notifBookmarked": [.zh: "收藏了你的帖子", .ja: "があなたの投稿を保存しました", .en: "bookmarked your post"],
        "systemNotification": [.zh: "系统通知", .ja: "システム通知", .en: "System notification"],
        "guide": [.zh: "指南", .ja: "ガイド", .en: "Guide"],
        "guideOpenFailed": [.zh: "指南暂时无法打开。", .ja: "ガイドを開けません。", .en: "Guide cannot be opened right now."],
        "machiOfficial": [.zh: "Machi 官方", .ja: "Machi 公式", .en: "Machi Official"],
        "cityAssistant": [.zh: "城市助手", .ja: "街のアシスタント", .en: "City Assistant"],
        "editorialCurated": [.zh: "编辑部整理", .ja: "編集部まとめ", .en: "Editorial"],
        "localLifeDesk": [.zh: "本地生活编辑部", .ja: "ローカルライフ編集部", .en: "Local Life Desk"],
        "language": [.zh: "语言", .ja: "言語", .en: "Language"],
        "appearance": [.zh: "外观", .ja: "外観", .en: "Appearance"],
        "logout": [.zh: "退出登录", .ja: "ログアウト", .en: "Log out"],
        "ok": [.zh: "好", .ja: "OK", .en: "OK"],
        "contentManagement": [.zh: "内容管理", .ja: "コンテンツ管理", .en: "Content"],
        "preferences": [.zh: "偏好", .ja: "設定項目", .en: "Preferences"],
        "security": [.zh: "安全", .ja: "セキュリティ", .en: "Security"],
        "privacyAndSafety": [.zh: "隐私与安全", .ja: "プライバシーと安全", .en: "Privacy and safety"],
        "support": [.zh: "支持", .ja: "サポート", .en: "Support"],
        "myPosts": [.zh: "我的投稿", .ja: "自分の投稿", .en: "My posts"],
        "drafts": [.zh: "草稿箱", .ja: "下書き", .en: "Drafts"],
        "mediaLibrary": [.zh: "媒体库", .ja: "メディアライブラリ", .en: "Media library"],
        "savedItems": [.zh: "条收藏内容", .ja: "件の保存", .en: "saved items"],
        "likedItems": [.zh: "条喜欢内容", .ja: "件のいいね", .en: "liked items"],
        "navigationReady": [.zh: "已就绪", .ja: "準備完了", .en: "Ready"],
        "comingSoon": [.zh: "即将推出", .ja: "近日公開", .en: "Coming soon"],
        "currentLanguage": [.zh: "当前界面语言", .ja: "現在の表示言語", .en: "Current interface language"],
        "appearanceSubtitle": [.zh: "跟随系统、浅色或深色", .ja: "システム、ライト、ダーク", .en: "System, light, or dark"],
        "notificationSettings": [.zh: "通知设置", .ja: "通知設定", .en: "Notification settings"],
        "notifPermissionOff": [.zh: "系统通知权限未开启，横幅和角标不会显示。", .ja: "通知の許可がオフのため、バナーとバッジは表示されません。", .en: "System notifications are off — banners and badges won't show."],
        "openSystemSettings": [.zh: "去系统设置开启", .ja: "設定アプリで開く", .en: "Open Settings"],
        "privacyProtectTitle": [.zh: "账号保护模式", .ja: "アカウント保護モード", .en: "Protected account"],
        "privacyProtectSub": [.zh: "开启后非粉丝无法查看你的帖子。", .ja: "オンにするとフォロワー以外はあなたの投稿を見られません。", .en: "When on, only followers can see your posts."],
        "dmPermission": [.zh: "谁可以私信我", .ja: "DM を受け取る相手", .en: "Who can message me"],
        "dmEveryone": [.zh: "所有人", .ja: "全員", .en: "Everyone"],
        "dmFollowing": [.zh: "我关注的人", .ja: "フォロー中の人", .en: "People I follow"],
        "dmNobody": [.zh: "不接收", .ja: "受け取らない", .en: "Nobody"],
        "dmPrivacyFootnote": [.zh: "由服务器强制执行。商品、租房等业务咨询会话不受影响。", .ja: "サーバー側で適用されます。出品・賃貸などの問い合わせには影響しません。", .en: "Enforced by the server. Listing-inquiry conversations are not affected."],
        "notifMessaged": [.zh: "给你发来私信", .ja: "がメッセージを送りました", .en: "sent you a message"],
        "inquiriesTitle": [.zh: "咨询管理", .ja: "問い合わせ管理", .en: "Inquiries"],
        "inquiriesSubtitle": [.zh: "收到和发出的咨询、应聘与预约", .ja: "送受信した問い合わせ・応募・予約", .en: "Received and sent inquiries, applications, bookings"],
        "inquiriesReceived": [.zh: "收到", .ja: "受信", .en: "Received"],
        "inquiriesSent": [.zh: "发出", .ja: "送信", .en: "Sent"],
        "inquiriesEmpty": [.zh: "暂无咨询", .ja: "問い合わせはまだありません", .en: "No inquiries yet"],
        "inquiriesEmptyHelp": [.zh: "有人联系你的发布时会出现在这里。", .ja: "あなたの投稿への連絡がここに表示されます。", .en: "Contacts about your listings will show up here."],
        "inquiryGeneral": [.zh: "咨询", .ja: "問い合わせ", .en: "Inquiry"],
        "inquiryListingGone": [.zh: "（信息已删除）", .ja: "（投稿は削除されました）", .en: "(listing removed)"],
        "ordersTitle": [.zh: "我的订单", .ja: "注文履歴", .en: "My orders"],
        "ordersSubtitle": [.zh: "会员购买与支付记录", .ja: "メンバーシップの購入・支払い履歴", .en: "Membership purchases and payments"],
        "ordersEmpty": [.zh: "暂无订单", .ja: "注文はまだありません", .en: "No orders yet"],
        "ordersEmptyHelp": [.zh: "开通会员后,订单会出现在这里。", .ja: "メンバーシップ購入後にここに表示されます。", .en: "Orders appear here after a purchase."],
        "orderPaid": [.zh: "已支付", .ja: "支払い済み", .en: "Paid"],
        "orderPending": [.zh: "待支付", .ja: "未払い", .en: "Pending"],
        "orderFailed": [.zh: "失败", .ja: "失敗", .en: "Failed"],
        "orderRefunded": [.zh: "已退款", .ja: "返金済み", .en: "Refunded"],
        "orderClosed": [.zh: "已关闭", .ja: "終了", .en: "Closed"],
        "memberLibraryTitle": [.zh: "会员资料库", .ja: "メンバー資料ライブラリ", .en: "Member library"],
        "memberLibrarySubtitle": [.zh: "30+ 份清单、模板与备考资料，会员免费查看", .ja: "30以上のチェックリスト・テンプレート・教材を会員は無料で閲覧", .en: "30+ checklists, templates and study packs included with membership"],
        "notifInquired": [.zh: "咨询了你的发布", .ja: "があなたの投稿に問い合わせました", .en: "inquired about your listing"],
        "settingsSyncFailed": [.zh: "设置已保存到本机，稍后会自动同步。", .ja: "設定は端末に保存されました。後で自動同期します。", .en: "Saved on this device; will sync later."],
        "privacySettings": [.zh: "隐私设置", .ja: "プライバシー設定", .en: "Privacy settings"],
        "privacySettingsSubtitle": [.zh: "主页可见范围和私信权限", .ja: "プロフィール公開範囲とメッセージ権限", .en: "Profile visibility and message permissions"],
        "recommendationSettings": [.zh: "内容推荐设置", .ja: "おすすめ設定", .en: "Recommendation settings"],
        "enabled": [.zh: "已开启", .ja: "オン", .en: "On"],
        "public": [.zh: "公开", .ja: "公開", .en: "Public"],
        "loginDevices": [.zh: "登录设备", .ja: "ログイン端末", .en: "Login devices"],
        "loginDevicesSubtitle": [.zh: "查看并撤销其他登录设备", .ja: "他のログイン端末を確認・取り消し", .en: "Review and revoke other devices"],
        "blocklist": [.zh: "黑名单", .ja: "ブロックリスト", .en: "Blocklist"],
        "blocklistSubtitle": [.zh: "管理不想看到或联系的人", .ja: "表示・連絡を避けたいユーザーを管理", .en: "Manage blocked people"],
        "dataExport": [.zh: "数据导出", .ja: "データ書き出し", .en: "Data export"],
        "clearCache": [.zh: "清除缓存", .ja: "キャッシュ削除", .en: "Clear cache"],
        "clearCacheSubtitle": [.zh: "清除图片和视频缓存", .ja: "画像と動画のキャッシュを削除", .en: "Clear image and video cache"],
        "helpCenter": [.zh: "帮助中心", .ja: "ヘルプセンター", .en: "Help center"],
        "feedback": [.zh: "反馈问题", .ja: "フィードバック", .en: "Feedback"],
        "aboutKaiX": [.zh: "关于 Machi", .ja: "Machi について", .en: "About Machi"],
        "developerInfo": [.zh: "开发者信息", .ja: "開発者情報", .en: "Developer info"],
        "deleteAccount": [.zh: "删除账号", .ja: "アカウント削除", .en: "Delete account"],
        "deleteAccountSubtitle": [.zh: "需要二次确认", .ja: "二段階確認が必要です", .en: "Requires second confirmation"],
        "version": [.zh: "版本", .ja: "バージョン", .en: "Version"],
        // Legal & support (App Store: Privacy Policy + Terms must be reachable in-app)
        "legalAndSupport": [.zh: "条款与支持", .ja: "規約とサポート", .en: "Legal & support"],
        "privacyPolicy": [.zh: "隐私政策", .ja: "プライバシーポリシー", .en: "Privacy Policy"],
        "termsOfService": [.zh: "用户协议", .ja: "利用規約", .en: "Terms of Service"],
        "commercialDisclosure": [.zh: "商业披露", .ja: "特定商取引法に基づく表記", .en: "Commercial Disclosure"],
        "contactSupport": [.zh: "联系支持", .ja: "サポートに連絡", .en: "Contact support"],
        "supportEmailLabel": [.zh: "支持邮箱", .ja: "サポートメール", .en: "Support email"],
        "creator": [.zh: "创作者", .ja: "クリエイター", .en: "Creator"],
        "member": [.zh: "普通用户", .ja: "一般ユーザー", .en: "Regular user"],
        "regularUser": [.zh: "普通用户", .ja: "一般ユーザー", .en: "Regular user"],
        "machiVerifiedMember": [.zh: "Machi 认证会员", .ja: "Machi 認証メンバー", .en: "Machi Verified"],
        "bio": [.zh: "简介", .ja: "自己紹介", .en: "Bio"],
        "location": [.zh: "地区", .ja: "地域", .en: "Location"],
        "avatarStyle": [.zh: "头像样式", .ja: "アイコンスタイル", .en: "Avatar style"],
        "avatarAndCover": [.zh: "头像与封面", .ja: "アイコンとカバー", .en: "Avatar and cover"],
        "chooseAvatar": [.zh: "选择头像", .ja: "アイコンを選択", .en: "Choose avatar"],
        "chooseCover": [.zh: "选择封面", .ja: "カバーを選択", .en: "Choose cover"],
        "currentPassword": [.zh: "当前密码", .ja: "現在のパスワード", .en: "Current password"],
        "newPassword": [.zh: "新密码", .ja: "新しいパスワード", .en: "New password"],
        "confirmPassword": [.zh: "确认密码", .ja: "パスワード確認", .en: "Confirm password"],
        "saveUsername": [.zh: "保存用户名", .ja: "ユーザー名を保存", .en: "Save username"],
        "usernameUpdated": [.zh: "用户名已更新。", .ja: "ユーザー名を更新しました。", .en: "Username updated."],
        "usernameValidationMessage": [.zh: "用户名不能为空，请使用字母、数字、下划线或点号。", .ja: "ユーザー名を入力してください。英数字、アンダースコア、ドットが使えます。", .en: "Username is required. Use letters, numbers, underscores, or dots."],
        "usernameWillNormalize": [.zh: "保存时会自动转为可用的账号格式。", .ja: "保存時に利用可能な形式へ整えます。", .en: "The username will be normalized when saved."],
        "savePassword": [.zh: "保存密码", .ja: "パスワードを保存", .en: "Save password"],
        "passwordValidationMessage": [.zh: "密码至少 8 位，包含字母和数字，且两次输入需要一致。", .ja: "パスワードは8文字以上で英字と数字を含み、確認と一致する必要があります。", .en: "Password must be at least 8 characters, include letters and numbers, and match confirmation."],
        "currentPasswordIncorrect": [.zh: "当前密码不正确。", .ja: "現在のパスワードが正しくありません。", .en: "Current password is incorrect."],
        "passwordSameAsOld": [.zh: "新密码不能与当前密码相同。", .ja: "新しいパスワードは現在のものと同じにできません。", .en: "New password cannot be the same as the current password."],
        "passwordUpdated": [.zh: "密码已更新。", .ja: "パスワードを更新しました。", .en: "Password updated."],
        "phone": [.zh: "手机号", .ja: "電話番号", .en: "Phone"],
        "saveEmail": [.zh: "保存邮箱", .ja: "メールを保存", .en: "Save email"],
        "emailValidationMessage": [.zh: "请填写有效邮箱。", .ja: "有効なメールアドレスを入力してください。", .en: "Enter a valid email address."],
        "emailUpdated": [.zh: "邮箱已更新并同步。", .ja: "メールを更新して同期しました。", .en: "Email updated and synced."],
        "contactStored": [.zh: "邮箱会同步到账号；手机号暂时只保存在本机。", .ja: "メールはアカウントへ同期され、電話番号は端末に保存されます。", .en: "Email syncs to your account; phone stays on this device for now."],
        "notVerified": [.zh: "未认证", .ja: "未認証", .en: "Not verified"],
        "memberVerificationHelp": [.zh: "当前为普通成员，可继续完善资料后申请创作者认证。", .ja: "現在は一般メンバーです。プロフィールを整えて認証を申請できます。", .en: "This account is a member. Complete the profile to apply for creator verification."],
        "creatorAccountHelp": [.zh: "当前账号具备创作者身份。", .ja: "このアカウントはクリエイター権限を持っています。", .en: "This account has creator status."],
        "applyVerification": [.zh: "申请认证", .ja: "認証を申請", .en: "Apply for verification"],
        "alreadyVerifiedMessage": [.zh: "当前账号已认证。", .ja: "このアカウントは認証済みです。", .en: "This account is already verified."],
        "verificationSaved": [.zh: "认证申请已保存。", .ja: "認証申請を保存しました。", .en: "Verification request saved."],
        "systemAppearance": [.zh: "跟随系统", .ja: "システム", .en: "System"],
        "lightAppearance": [.zh: "浅色", .ja: "ライト", .en: "Light"],
        "darkAppearance": [.zh: "深色", .ja: "ダーク", .en: "Dark"],
        "likeNotifications": [.zh: "点赞通知", .ja: "いいね通知", .en: "Like notifications"],
        "commentNotifications": [.zh: "评论通知", .ja: "コメント通知", .en: "Comment notifications"],
        "repostNotifications": [.zh: "转发通知", .ja: "リポスト通知", .en: "Repost notifications"],
        "followNotifications": [.zh: "关注通知", .ja: "フォロー通知", .en: "Follow notifications"],
        "messageNotifications": [.zh: "私信通知", .ja: "メッセージ通知", .en: "Message notifications"],
        "systemNotifications": [.zh: "系统通知", .ja: "システム通知", .en: "System notifications"],
        "profileVisibility": [.zh: "主页可见范围", .ja: "プロフィール公開範囲", .en: "Profile visibility"],
        "followersOnly": [.zh: "仅关注者", .ja: "フォロワーのみ", .en: "Followers only"],
        "onlyMe": [.zh: "仅自己", .ja: "自分のみ", .en: "Only me"],
        "allowStrangerMessages": [.zh: "允许陌生人私信", .ja: "知らない人からのメッセージを許可", .en: "Allow messages from strangers"],
        "recommendLocalLife": [.zh: "推荐本地生活", .ja: "ローカル生活をおすすめ", .en: "Recommend local life"],
        "recommendNews": [.zh: "推荐新闻资讯", .ja: "ニュースをおすすめ", .en: "Recommend news"],
        "recommendTech": [.zh: "增加技术内容", .ja: "技術コンテンツを増やす", .en: "Include more tech"],
        "currentDevice": [.zh: "iPhone 17 Pro · 当前设备", .ja: "iPhone 17 Pro · 現在の端末", .en: "iPhone 17 Pro · Current device"],
        "lastActiveNow": [.zh: "最后活动：刚刚", .ja: "最終アクティブ：たった今", .en: "Last active: just now"],
        "noBlockedUsers": [.zh: "当前没有拉黑用户。", .ja: "ブロック中のユーザーはいません。", .en: "No blocked users."],
        "revoke": [.zh: "撤销", .ja: "取り消す", .en: "Revoke"],
        "revokeDeviceConfirm": [.zh: "撤销这个登录设备？", .ja: "この端末のログインを取り消しますか？", .en: "Revoke this device?"],
        "deviceRevoked": [.zh: "已撤销", .ja: "取り消しました", .en: "Revoked"],
        "noOtherDevices": [.zh: "只有当前设备登录。", .ja: "現在の端末のみログイン中。", .en: "Only this device is signed in."],
        "localDataSummary": [.zh: "本机数据摘要", .ja: "ローカルデータ概要", .en: "Local data summary"],
        "generateExport": [.zh: "生成导出包", .ja: "書き出しパッケージを作成", .en: "Generate export"],
        "exportSummaryGenerated": [.zh: "导出摘要已生成。", .ja: "書き出し概要を生成しました。", .en: "Export summary generated."],
        "cacheDescription": [.zh: "清除图片和视频缩略图缓存，不会删除帖子、私信或账号数据。", .ja: "画像と動画サムネイルのキャッシュを削除します。投稿、メッセージ、アカウントは削除されません。", .en: "Clears image and video thumbnail cache without deleting posts, messages, or account data."],
        "clearCacheConfirm": [.zh: "确认清除缓存？", .ja: "キャッシュを削除しますか？", .en: "Clear cache?"],
        "cacheCleared": [.zh: "缓存已清除。", .ja: "キャッシュを削除しました。", .en: "Cache cleared."],
        "faq": [.zh: "常见问题", .ja: "よくある質問", .en: "FAQ"],
        "helpPublishMedia": [.zh: "发布失败时请检查相册权限、媒体文件大小和本地数据库状态。", .ja: "投稿に失敗した場合は、写真権限、メディアサイズ、ローカルDB状態を確認してください。", .en: "If posting fails, check photo permissions, media size, and local database state."],
        "helpLocalData": [.zh: "私信、关注、评论和收藏都会保存在本机数据库中。", .ja: "メッセージ、フォロー、コメント、保存はローカルDBに保存されます。", .en: "Messages, follows, comments, and bookmarks are saved in the local database."],
        "feedbackPlaceholder": [.zh: "描述你遇到的问题", .ja: "発生した問題を説明", .en: "Describe the issue"],
        "submitFeedback": [.zh: "提交反馈", .ja: "送信", .en: "Submit feedback"],
        "feedbackSaved": [.zh: "感谢反馈，我们已收到。", .ja: "フィードバックを受け取りました。ありがとうございます。", .en: "Thanks — we received your feedback."],
        "feedbackSending": [.zh: "提交中…", .ja: "送信中…", .en: "Sending…"],
        "feedbackFailed": [.zh: "提交失败，请稍后重试。", .ja: "送信に失敗しました。後でもう一度お試しください。", .en: "Couldn't send. Please try again later."],
        "aboutSubtitle": [.zh: "社交新闻生活 App · 本地优先社区体验", .ja: "ソーシャルニュース生活アプリ · ローカルファーストのコミュニティ体験", .en: "Social news and lifestyle app · Local-first community experience"],
        "architecture": [.zh: "架构", .ja: "アーキテクチャ", .en: "Architecture"],
        "developerArchitectureText": [.zh: "数据层、上传服务、图片缓存、视频缩略图和热度计算均已拆分。", .ja: "データ層、アップロード、画像キャッシュ、動画サムネイル、ヒート計算を分離しています。", .en: "Data, uploads, image cache, video thumbnails, and heat scoring are separated."],
        "databaseStatus": [.zh: "数据库状态", .ja: "データベース状態", .en: "Database status"],
        "online": [.zh: "在线", .ja: "オンライン", .en: "Online"],
        "currentUserId": [.zh: "当前用户 ID", .ja: "現在のユーザー ID", .en: "Current user ID"],
        "userCount": [.zh: "用户数量", .ja: "ユーザー数", .en: "Users"],
        "postCount": [.zh: "帖子数量", .ja: "投稿数", .en: "Posts"],
        "commentCount": [.zh: "评论数量", .ja: "コメント数", .en: "Comments"],
        "notificationCount": [.zh: "通知数量", .ja: "通知数", .en: "Notifications"],
        "threadCount": [.zh: "私信会话数量", .ja: "メッセージスレッド数", .en: "Message threads"],
        "deleteAccountDescription": [.zh: "删除账号会同步到服务器，并从本机移除该账号、帖子、评论、私信和相关通知。此操作不可撤销。", .ja: "アカウント削除はサーバーへ同期され、この端末からアカウント、投稿、コメント、メッセージ、通知も削除します。取り消せません。", .en: "Deleting the account syncs to the server and removes the account, posts, comments, messages, and notifications from this device. This cannot be undone."],
        "notSet": [.zh: "未设置", .ja: "未設定", .en: "Not set"],
        "enterDelete": [.zh: "输入 DELETE 确认", .ja: "DELETE と入力して確認", .en: "Type DELETE to confirm"],
        "secondDeleteConfirm": [.zh: "二次确认删除账号？", .ja: "本当にアカウントを削除しますか？", .en: "Confirm account deletion?"],
        "confirmDelete": [.zh: "确认删除", .ja: "削除を確認", .en: "Confirm delete"],
        "newConversationsHere": [.zh: "新的对话会显示在这里。", .ja: "新しい会話がここに表示されます。", .en: "New conversations will appear here."],
        "notificationsHere": [.zh: "点赞、评论、关注和系统消息会显示在这里。", .ja: "いいね、コメント、フォロー、システム通知がここに表示されます。", .en: "Likes, comments, follows, and system messages will appear here."],
        "saveDraft": [.zh: "保存草稿", .ja: "下書き保存", .en: "Save draft"],
        "draftSaved": [.zh: "草稿已保存", .ja: "下書きを保存しました", .en: "Draft saved"],
        "publishDraft": [.zh: "发布草稿", .ja: "下書きを投稿", .en: "Publish draft"],
        "deleteDraft": [.zh: "删除草稿", .ja: "下書きを削除", .en: "Delete draft"],
        "continueEdit": [.zh: "继续编辑", .ja: "編集を続ける", .en: "Continue editing"],
        "draftsEmpty": [.zh: "暂无草稿", .ja: "下書きはありません", .en: "No drafts"],
        "draftsHelp": [.zh: "取消投稿时选择保存草稿，会出现在这里。", .ja: "投稿をキャンセルして下書き保存するとここに表示されます。", .en: "Saved drafts from compose will appear here."],
        "bookmarkEmptyHelp": [.zh: "收藏过的帖子会集中显示在这里。", .ja: "保存した投稿がここに表示されます。", .en: "Bookmarked posts will appear here."],
        "mediaEmptyHelp": [.zh: "你发布过的图片和视频会显示在这里。", .ja: "投稿した画像や動画がここに表示されます。", .en: "Your posted photos and videos will appear here."],
        "all": [.zh: "全部", .ja: "すべて", .en: "All"],
        "interactionNotifications": [.zh: "互动", .ja: "リアクション", .en: "Activity"],
        "system": [.zh: "系统", .ja: "システム", .en: "System"],
        "viewMoreReplies": [.zh: "展开更多回复", .ja: "返信をもっと見る", .en: "View more replies"],
        "hideReplies": [.zh: "收起回复", .ja: "返信を閉じる", .en: "Hide replies"],
        "replies": [.zh: "回复", .ja: "返信", .en: "Replies"],
        "topicHot": [.zh: "热门", .ja: "人気", .en: "Hot"],
        "topicLatest": [.zh: "最新", .ja: "最新", .en: "Latest"],
        "topicHighHeat": [.zh: "高热度", .ja: "高ヒート", .en: "High heat"],
        "topicContributors": [.zh: "贡献者", .ja: "投稿者", .en: "Contributors"],
        "relatedCities": [.zh: "相关城市", .ja: "関連都市", .en: "Related cities"],
        "topicMedia": [.zh: "媒体", .ja: "メディア", .en: "Media"],
        "participants": [.zh: "参与用户", .ja: "参加ユーザー", .en: "participants"],
        "topicIntro": [.zh: "来自社区的实时讨论和生活信息。", .ja: "コミュニティのリアルタイムな話題と生活情報です。", .en: "Live community discussion and local updates."],
        "cityDescRecommend": [.zh: "该城市综合推荐流，混合动态、新闻、攻略、交易、租房、工作、活动和服务。", .ja: "この都市の総合おすすめです。", .en: "Mixed recommended local posts for this city."],
        "cityDescDynamic": [.zh: "本地生活记录、图文、吐槽、观点和城市见闻。", .ja: "暮らしの記録、写真、意見、街の発見。", .en: "Local life notes, photos, opinions, and city moments."],
        "cityDescNews": [.zh: "本地新闻、快讯、政策提醒、交通提醒、安全提醒、学校通知和活动快讯。", .ja: "地域ニュース、交通、安全、学校、イベント速報。", .en: "Local news, alerts, policy, traffic, safety, campus, and event updates."],
        "cityDescGuide": [.zh: "租房、求职、签证、交通、银行卡、手机卡、医院、报税、搬家和生活成本攻略。", .ja: "住居、仕事、ビザ、交通、銀行、携帯、病院、税、引越しガイド。", .en: "Guides for housing, jobs, visa, transit, banking, phone plans, healthcare, tax, and moving."],
        "cityDescSecondhand": [.zh: "闲置转让、求购、家具、家电、电子产品、教材、搬家甩卖和免费赠送。", .ja: "中古品、家具、家電、教材、引越し処分、無料譲渡。", .en: "Secondhand sales, wanted posts, furniture, appliances, electronics, books, moving sales, and giveaways."],
        "cityDescHousing": [.zh: "找房、转租、合租、找室友、房源分享、租房避坑、区域推荐和中介评价。", .ja: "部屋探し、転貸、シェア、ルームメイト、賃貸注意点。", .en: "Housing, sublets, shares, roommates, listings, rental warnings, neighborhood notes, and agent reviews."],
        "cityDescJobSeek": [.zh: "求职帖、找兼职、找全职、找实习、找远程、简历求助、面试经验和工资避坑。", .ja: "求職、アルバイト、正社員、インターン、リモート、面接経験。", .en: "Job seeking, part-time, full-time, internship, remote work, resume help, interview notes, and salary warnings."],
        "cityDescJobPost": [.zh: "企业招聘、商家招聘、兼职、全职、实习、远程招聘和内推信息。", .ja: "企業・店舗求人、アルバイト、正社員、インターン、リモート、紹介。", .en: "Company and merchant hiring, part-time, full-time, internships, remote jobs, and referrals."],
        "cityDescMeetup": [.zh: "学习小组、运动小组、摄影小组、语言交换、游戏小组和本地活动。", .ja: "学習グループ、運動、写真、言語交換、ゲーム、地域活動。", .en: "Study groups, sports groups, photo walks, language exchange, gaming groups, and local activity posts."],
        "cityDescDining": [.zh: "美食聚会、咖啡、探店和周末本地餐厅讨论。", .ja: "食事の集まり、カフェ、店巡り、週末の飲食店情報。", .en: "Food meetups, coffee, restaurant visits, and weekend dining discussions."],
        "cityDescEvent": [.zh: "桌游、摄影、学习局、运动、Citywalk、展览、音乐节、线下聚会和创业交流。", .ja: "ボードゲーム、写真、勉強会、運動、街歩き、展示、音楽、交流会。", .en: "Board games, photo walks, study groups, sports, citywalks, exhibitions, music, offline gatherings, and founder meetups."],
        "cityDescQuestion": [.zh: "本地生活求助、签证、租房、工作、学校、医疗和交通问题。", .ja: "生活、ビザ、賃貸、仕事、学校、医療、交通の質問。", .en: "Local help for life, visa, housing, jobs, schools, healthcare, and transit."],
        "cityDescService": [.zh: "餐饮预约、住宿短住、旅行票务、接送交通、翻译手续、搬家清洁、生活开通和美容健康预约。", .ja: "飲食予約、宿泊・短期滞在、旅行チケット、送迎、翻訳・手続き、引越し清掃、生活手続き、美容・健康予約。", .en: "Dining bookings, stays, travel tickets, transfers, paperwork, moving, life setup, and beauty or health booking support."],
        "cityDescMerchant": [.zh: "餐厅、咖啡店、住宿短住、旅行票务、接送交通、翻译手续、美容健康和本地店铺。", .ja: "飲食店、カフェ、宿泊・短期滞在、旅行チケット、送迎、翻訳・手続き、美容・健康、地元店舗。", .en: "Restaurants, cafes, stays, travel tickets, transfers, paperwork, beauty and local shops."],
        "cityDescCoupon": [.zh: "商家优惠、折扣、团购、优惠券和限时活动。", .ja: "店舗割引、クーポン、共同購入、期間限定キャンペーン。", .en: "Merchant deals, discounts, group buys, coupons, and limited-time offers."],
        "cityDescWarning": [.zh: "租房避坑、工作避坑、交易提醒、防骗提醒和消费纠纷经验，支持举报和审核。", .ja: "賃貸・仕事・取引の注意喚起、詐欺防止、消費トラブル。", .en: "Housing, work, transaction, anti-scam, and consumer dispute warnings with report and review support."],
        "cityDescHot": [.zh: "该城市 24 小时内高热度内容，按点赞、评论、转发、收藏、举报和加热权重排序。", .ja: "この都市の24時間以内の急上昇投稿。", .en: "High-heat posts in this city from the last 24 hours."],
        "images": [.zh: "图片", .ja: "画像", .en: "Images"],
        "videos": [.zh: "视频", .ja: "動画", .en: "Videos"],
        // Machi Verified membership
        "done": [.zh: "完成", .ja: "完了", .en: "Done"],
        "membershipTitle": [.zh: "Machi 认证会员", .ja: "Machi 認証メンバー", .en: "Machi Verified"],
        "membershipSubtitle": [.zh: "让你的发布更可信，也让更多人看见你。", .ja: "あなたの投稿をより信頼され、より多くの人に届けます。", .en: "Make your posts more trusted — and seen by more people."],
        "membershipPriceUnit": [.zh: "/ 月", .ja: "/ 月", .en: "/ month"],
        "membershipBenefitsTitle": [.zh: "会员权益", .ja: "メンバー特典", .en: "What you get"],
        "membershipBenefitBadge": [.zh: "昵称旁显示认证标识", .ja: "名前の横に認証バッジを表示", .en: "A verified badge next to your name"],
        "membershipBenefitPublish": [.zh: "可发布招聘、租房、本地服务等高信任内容", .ja: "求人・住まい・地域サービスなど信頼性の高い投稿が可能", .en: "Post jobs, housing, local services and other high-trust content"],
        "membershipBenefitPriority": [.zh: "内容获得轻微优先展示", .ja: "表示順がわずかに優遇", .en: "A gentle boost in ranking"],
        "membershipBenefitData": [.zh: "查看基础内容数据", .ja: "投稿の基本データを閲覧", .en: "Basic stats on your posts"],
        "membershipBenefitQuota": [.zh: "更高每日发布额度", .ja: "1日の投稿上限がアップ", .en: "A higher daily posting limit"],
        "membershipBenefitReview": [.zh: "优先进入审核队列", .ja: "審査キューで優先", .en: "Priority in the review queue"],
        "membershipBenefitAudience": [.zh: "适合招聘方、房源发布者、本地服务商和高频发布用户", .ja: "採用担当・物件オーナー・地域の事業者・よく投稿する方に最適", .en: "Great for recruiters, landlords, local merchants and frequent posters"],
        "membershipSafetyNotice": [.zh: "认证会员不代表平台担保交易真实性。租房、招聘、二手和线下见面仍需谨慎核实。", .ja: "認証メンバーはプラットフォームが真実性を保証するものではありません。住まい・求人・中古取引・対面では十分にご確認ください。", .en: "Verified status is not a platform guarantee of authenticity. Stay careful with housing, jobs, second-hand deals and in-person meetups."],
        "membershipCTA": [.zh: "开通认证会员", .ja: "認証メンバーになる", .en: "Get Verified"],
        "membershipRestore": [.zh: "恢复购买", .ja: "購入を復元", .en: "Restore Purchase"],
        "membershipActiveTitle": [.zh: "你已是 Machi 认证会员", .ja: "あなたは Machi 認証メンバーです", .en: "You're a Machi Verified member"],
        "membershipActiveUntil": [.zh: "有效期至", .ja: "有効期限", .en: "Active until"],
        "membershipStatusActive": [.zh: "已认证", .ja: "認証済み", .en: "Verified"],
        "membershipPurchasePending": [.zh: "支付处理中，完成后会自动开通。", .ja: "支払い処理中です。完了後に自動的に有効になります。", .en: "Payment is pending; it will activate automatically once complete."],
        "membershipPurchaseFailed": [.zh: "购买未完成，请重试。", .ja: "購入が完了しませんでした。もう一度お試しください。", .en: "Purchase didn't complete. Please try again."],
        // Auto-renewable subscription disclosure (App Store Review 3.1.2)
        "membershipRenewalDisclosure": [
            .zh: "订阅为自动续订。确认购买后将向你的 Apple ID 收费；除非在当前周期结束前至少 24 小时关闭自动续订，否则会按所选周期（按月或包年）自动续期并收费。",
            .ja: "本サブスクリプションは自動更新です。購入確定時に Apple ID へ課金され、期間終了の24時間以上前に自動更新をオフにしない限り、選択した期間（月額または年額）で自動的に更新・課金されます。",
            .en: "This subscription auto-renews. Your Apple ID is charged on confirmation and renews at the selected period (monthly or yearly) unless auto-renew is turned off at least 24 hours before the period ends."
        ],
        "membershipManage": [.zh: "管理订阅", .ja: "サブスクリプションを管理", .en: "Manage subscription"],
        "membershipCancelNote": [
            .zh: "可随时在「设置 › Apple ID › 订阅」中取消，已付费的当前周期仍可继续使用至到期。",
            .ja: "「設定 › Apple ID › サブスクリプション」からいつでも解約できます。お支払い済みの当該期間は満了まで利用できます。",
            .en: "Cancel anytime in Settings › Apple ID › Subscriptions. Paid time remains usable until the current period ends."
        ],
        "membershipSettingsTitle": [.zh: "Machi 认证会员", .ja: "Machi 認証メンバー", .en: "Machi Verified"],
        "membershipSettingsSubtitle": [.zh: "蓝色认证标识与高信任内容发布权限", .ja: "認証バッジと信頼性の高い投稿権限", .en: "Verified badge and high-trust posting"],
        "composeMembershipRequired": [.zh: "发布招聘、租房和本地服务等高信任内容，需要开通 Machi 认证会员。", .ja: "求人・住まい・地域サービスなど信頼性の高い投稿には Machi 認証メンバーが必要です。", .en: "Posting jobs, housing, local services and other high-trust content requires Machi Verified."],
        "composeMembershipCTA": [.zh: "查看认证会员套餐", .ja: "認証メンバープランを見る", .en: "View Verified plans"],
        "membershipBenefitSync": [.zh: "多端通用 · iOS 与网页一次开通、全站认证标识", .ja: "マルチ端末対応 — iOS と Web 共通、認証バッジは全体表示", .en: "Use everywhere — one purchase covers iOS + web, badge site-wide"],
        "membershipInsightsTitle": [.zh: "内容数据", .ja: "コンテンツ統計", .en: "Your content stats"],
        "membershipInsightsPosts": [.zh: "发布", .ja: "投稿", .en: "Posts"],
        "membershipInsightsViews": [.zh: "浏览", .ja: "閲覧", .en: "Views"],
        "membershipInsightsLikes": [.zh: "点赞", .ja: "いいね", .en: "Likes"],
        "membershipInsightsBookmarks": [.zh: "收藏", .ja: "保存", .en: "Saves"],
        "membershipInsightsComments": [.zh: "评论", .ja: "コメント", .en: "Comments"]
    ]

    func localized(_ key: String, language: AppLanguage) -> String {
        table[key]?[language] ?? table[key]?[.zh] ?? key
    }
}
