import Foundation

enum PostAttributeKeys {
    static let title = "title"
    static let price = "price"
    static let currency = "currency"
    static let condition = "condition"
    static let tradeMethod = "trade_method"
    static let area = "area"
    static let status = "status"
    static let category = "category"

    static let rent = "rent"
    static let rentRange = "rent_range"
    static let roomType = "room_type"
    static let nearestStation = "nearest_station"
    static let moveInDate = "move_in_date"
    static let deposit = "deposit"
    static let keyMoney = "key_money"
    static let contactMethod = "contact_method"
    static let lifestyleTags = "lifestyle_tags"
    static let requirements = "requirements"

    static let desiredJob = "desired_job"
    static let skills = "skills"
    static let languages = "languages"
    static let visaStatus = "visa_status"
    static let availability = "availability"
    static let expectedSalary = "expected_salary"
    static let resumeURL = "resume_url"
    static let jobTitle = "job_title"
    static let companyName = "company_name"
    static let salary = "salary"
    static let jobType = "job_type"
    static let languageRequirement = "language_requirement"
    static let visaRequirement = "visa_requirement"
    static let workLocation = "work_location"
    static let companyVerified = "company_verified"

    static let meetupType = "meetup_type"
    static let meetupTime = "meetup_time"
    static let location = "location"
    static let peopleLimit = "people_limit"
    static let budget = "budget"
    static let description = "description"
    static let safetyNotice = "safety_notice"

    static let eventTime = "event_time"
    static let fee = "fee"
    static let capacity = "capacity"
    static let registrationMethod = "registration_method"

    static let restaurantOrArea = "restaurant_or_area"
    static let source = "source"
    static let summary = "summary"
    static let content = "content"
    static let externalURL = "external_url"
    static let coverImage = "cover_image"
    static let lastUpdatedAt = "last_updated_at"
    static let serviceType = "service_type"
    static let priceRange = "price_range"
    static let merchantId = "merchant_id"
    static let verifiedStatus = "verified_status"
    static let merchantName = "merchant_name"
    static let merchantType = "merchant_type"
    static let address = "address"
    static let openingHours = "opening_hours"
    static let rating = "rating"
    static let discountInfo = "discount_info"
    static let validUntil = "valid_until"
    static let usageRules = "usage_rules"
    static let evidenceImages = "evidence_images"
    static let anonymous = "anonymous"
    static let reviewStatus = "review_status"
    static let question = "question"
    static let options = "options"
    static let expiresAt = "expires_at"
}
